### ISSUE TITLE
Compiling errors on adding new item

### ISSUE THREAD

**Issue by zkkitco** [ReversePOCO/EntityFramework-Reverse-POCO-Code-First-Generator#365]
Using Windows 7, VS 2013, .net 4.5.1, EF 6.1.1, EF tools installed.

I 'm trying to use this extension for the first time and when adding it as a new item to the project, I'm getting the following errors, and have no idea where to look for a solution. Any help would be greatly appreciated. Thank you.

Error	1	Compiling transformation: ; expected	c:\...\EF.Reverse.POCO.Core.ttinclude	3197	47	
Error	2	Compiling transformation: Invalid token '+' in class, struct, or interface member declaration	c:\...\EF.Reverse.POCO.Core.ttinclude	3197	64	
Error	3	Compiling transformation: Invalid token ';' in class, struct, or interface member declaration	c:\...\EF.Reverse.POCO.Core.ttinclude	3197	72	KVEC
Error	4	Compiling transformation: { expected	c:\...\EF.Reverse.POCO.Core.ttinclude	3247	47	KVEC
Error	5	Compiling transformation: Method must have a return type	c:\...\EF.Reverse.POCO.Core.ttinclude	3247	50	KVEC
Error	6	Compiling transformation: Identifier expected	c:\....\EF.Reverse.POCO.Core.ttinclude	3247	70	KVEC

**Comment by sjh37** [comment]
Hi. On the front page of this project: https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator Have you looked at installing this project guide? Specifically, you need to install https://www.microsoft.com/en-us/download/details.aspx?id=40762

**Comment by zkkitco** [comment]
I have installed the EF tools for VS 2013 from the link provided above.

**Comment by sjh37** [comment]
And is it working ok, or do you still have the problem?

**Comment by zkkitco** [comment]
Sorry, I meant I had it installed when I posted this issue initially.

**Comment by sjh37** [comment]
Is it a C# project using .Net 4.6? It sounds odd that you get compiler error. You are the first to have it.

Can you open the source code to this repository, and save the database.tt file. It may complain you don't have northwind database, but it should not give a compilation error like you are seeing

**Comment by zkkitco** [comment]
Using .net 4.5.1. I will try setting up a new project using 4.6

**Comment by zkkitco** [comment]
Same issues when using .Net 4.6 and 4.6.1.

**Comment by zkkitco** [comment]
Ok, now I'm wondering if the Entity Framework Tools 6.1.3 was actually installed correctly. I'm not seeing it listed in the installed products, under Help > About Microsoft Visual Studio. or in the Visual Studio tools folder. Would it be listed as something else?

**Comment by zkkitco** [comment]
I tried to save the database.tt file from the downloaded repository files and received the same compiler errors.

**Comment by sjh37** [comment]
I had a google about and came across:

- https://stackoverflow.com/questions/4945342/t4-for-sharp-architecture-northwind-problem
This said to remove all white spaces at the end of all the .tt and .ttinclude files.
Can you give that a go and let me know if it helps at all.

**Comment by zkkitco** [comment]
I have removed the spaces from the end of file, and ensured that all other line endings were normalized to cr lf, bu I'm getting the same errors.

**Comment by stinkyjak** [comment]
Using VS2017 15.5.3, EF 6.2.0, .net 4.6.1  

Version 2.33.0 worked flawlessly for me. 
I upgraded from 2.33.0 to 2.35.0 and this is no longer working for me either. 

`public string NameHumanCaseWithSuffix => NameHumanCase + Suffix;`

=> class member declaration expected. 


Severity	Code	Description	Project	File	Line	Suppression State
Error		Class member declaration expected.		C:\...\EF.Reverse.POCO.Core.ttinclude	3438	
Error		Class member declaration expected.		C:\...\EF.Reverse.POCO.Core.ttinclude	3438	
Error		Class member declaration expected.		C:\...\EF.Reverse.POCO.Core.ttinclude	3438	
Error		'{' expected.		C:\...\EF.Reverse.POCO.Core.ttinclude	3488	
Error		The constructor's name must match the containing type's name.	
 C:\...\EF.Reverse.POCO.Core.ttinclude	3488	
Error		Identifier expected.		C:\...\EF.Reverse.POCO.Core.ttinclude	3488

**Comment by stinkyjak** [comment]
This still generates the files. This only shows an error if I actually open the EF.Reverse.POCO.Core.ttinclude in VS.

**Comment by sjh37** [comment]
It's a C#7 compiler feature, being compiled by C#6.

try changing it to
```c#
public string NameHumanCaseWithSuffix { return NameHumanCase + Suffix; }
```

**Comment by stinkyjak** [comment]
Thank you sir. 

Changing to Latest(major) allowed this to build. 

My errors were from my t4 editor. Uninstalled tangible and no more errors. 
Again, thanks to everyone on this project.  I didn't mean to hijack this thread. I had the same original errors so google brought me here.

**Comment by sjh37** [comment]
Hi @zkkitco Can you try using the latest version of the project, and update `NameHumanCaseWithSuffix` to be:
```c#
public string NameHumanCaseWithSuffix { return NameHumanCase + Suffix; }
```

Can you let me know if this solves your problem?

**Comment by kimballjohnson** [comment]
Hi Simon,
I'm having these same problems, but with several lines in the ttinclude file. Do you have a version that is compatible with the syntax of .net 4.5.1?
Thanks,
Kimball

**Comment by sjh37** [comment]
@kimballjohnson I've just tried .net 4.5.1 with v2.35.0 on VS2017 and all seems to work fine. What version of the generator are you using?

**Comment by arbh89** [comment]
I think the problem is not the .net version, instead i think the problem is visual studio version, with VS2017 the template v2.35.0 is ok but with VS2013 fail because of C#  7 syntax.

**Comment by sjh37** [comment]
@arbh89 Hopefully all of these are now fixed in the latest code, I will make a release later today.

**Comment by sjh37** [comment]
@kimballjohnson I have just released v2.36.0. Hopefully this will fix all your C# 7 problems.

**Comment by sjh37** [comment]
Released in v2.36.0

**Comment by arbh89** [comment]
The problems persists in VS2013.

![image](https://user-images.githubusercontent.com/6992258/36688890-6af4779a-1af3-11e8-98af-eae421dba3d0.png)

![image](https://user-images.githubusercontent.com/6992258/36688904-7a36cf1e-1af3-11e8-97a0-95b391a7bb20.png)

**Comment by sjh37** [comment]
@arbh89 

Can you please change this function to 
```c#
        public Column this[string columnName]
        {
            get { return GetColumn(columnName); }
        }
```

Please let me know if there are any other compiler errors. Thanks for your help.

**Comment by arbh89** [comment]
@sjh37, i get this errors now.

![image](https://user-images.githubusercontent.com/6992258/36693658-a098eddc-1b01-11e8-8938-b91b91e59a2d.png)

**Comment by arbh89** [comment]
I was comparing the latest code with version 2.32.0 wich is the last that works in VS2013, i have replaced this code 
```csharp
    public class ForeignKey
    {
        public string FkTableName { get; }
        public string FkTableNameFiltered { get; }
        public string FkSchema { get; }
        public string PkTableName { get; }
        public string PkTableNameFiltered { get; }
        public string PkSchema { get; }
        public string FkColumn { get; }
        public string PkColumn { get; }
        public string ConstraintName { get; }
        public int Ordinal { get; }
        public bool CascadeOnDelete { get; }
        public bool IsNotEnforced { get; }
```
With this.

```csharp
    public class ForeignKey
    {
        public string FkTableName { get; private set; }
        public string FkTableNameFiltered { get; private set; }
        public string FkSchema { get; private set; }
        public string PkTableName { get; private set; }
        public string PkTableNameFiltered { get; private set; }
        public string PkSchema { get; private set; }
        public string FkColumn { get; private set; }
        public string PkColumn { get; private set; }
        public string ConstraintName { get; private set; }
        public int Ordinal { get; private set; }
        public bool CascadeOnDelete { get; private set; }
        public bool IsNotEnforced { get; private set; }
```

Now the error is this.

![image](https://user-images.githubusercontent.com/6992258/36695842-0db99046-1b08-11e8-99d4-1c609bc63b30.png)

```csharp
throw new ArgumentOutOfRangeException(nameof(relationship));

**Comment by arbh89** [comment]
I also replaced all lines containing "nameof" and leave it like version 2.32.0 and it is working now.

I am attaching the file so you can review the changes and consider merging.


[EF.Reverse.POCO.Core.ttinclude.txt](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/1760359/EF.Reverse.POCO.Core.ttinclude.txt)

**Comment by sjh37** [comment]
@arbh89 Thanks so much for your help. I have just released v2.36.1 and will be available within 15 minutes on the marketplace.

**Comment by okreka** [comment]
Also for me first time using it. In visual studio 2015, and i get the following error in EF.Reverse.POCO.CORE.ttinclude

Please any help.

![image](https://user-images.githubusercontent.com/33457418/42951593-d0a2dfc0-8b76-11e8-9fef-23c39f2ad5f3.png)

**Comment by sjh37** [comment]
That is using C# 7.

Add a line before the use of valueFromName to be:
string valueFromName, valuefromType;

then change
   out string valueFromName
to be
   out valueFromName;

do the same for valueFromType;

**Comment by sjh37** [comment]
Released in v2.37.1

**Comment by okreka** [comment]
I used v2.37.1 and everything is okay.
Thank you very much for your help!

**Comment by arbh89** [comment]
Is it possible to update WriteStoredProcFunctionDeclareSqlParameter to make it compatible with VS2013. I Have removed string interpolation feature.

```C#
public static readonly Func<StoredProcedure, bool, string> WriteStoredProcFunctionDeclareSqlParameter = (sp, includeProcResult) =>
    {
        var sb = new StringBuilder();
        foreach (var p in sp.Parameters.OrderBy(x => x.Ordinal))
        {
            var isNullable = !NotNullable.Contains(p.PropertyType.ToLower());
            var getValueOrDefault = isNullable ? ".GetValueOrDefault()" : string.Empty;
            var isGeography = p.PropertyType == "System.Data.Entity.Spatial.DbGeography";

            sb.AppendLine(
                string.Format("            var {0} = new System.Data.SqlClient.SqlParameter", WriteStoredProcSqlParameterName(p))
                + string.Format(" {{ ParameterName = \"{0}\", ", p.Name)
                + (isGeography ? "UdtTypeName = \"geography\"" : string.Format("SqlDbType = System.Data.SqlDbType.{0}", p.SqlDbType))
                + ", Direction = System.Data.ParameterDirection."
                + (p.Mode == StoredProcedureParameterMode.In ? "Input" : "Output")
                + (p.Mode == StoredProcedureParameterMode.In
                    ? ", Value = " + (isGeography
                        ? string.Format("Microsoft.SqlServer.Types.SqlGeography.Parse({0}.AsText())", p.NameHumanCase)
                        : p.NameHumanCase + getValueOrDefault)
                    : string.Empty)
                + (p.MaxLength != 0 ? ", Size = " + p.MaxLength : string.Empty)
                + ((p.Precision > 0 || p.Scale > 0) ? ", Precision = " + p.Precision + ", Scale = " + p.Scale : string.Empty)
                + (p.PropertyType.ToLower().Contains("datatable") ? ", TypeName = \"" + p.UserDefinedTypeName + "\"" : string.Empty)
                + " };");

                if (p.Mode == StoredProcedureParameterMode.In)
                {
                    sb.AppendFormat(
                        isNullable
                            ? "            if (!{0}.HasValue){1}                {0}Param.Value = System.DBNull.Value;{1}{1}"
                            : "            if ({0}Param.Value == null){1}                {0}Param.Value = System.DBNull.Value;{1}{1}",
                        p.NameHumanCase, Environment.NewLine);
                }
        }
        if(includeProcResult && sp.ReturnModels.Count < 2)
            sb.AppendLine("            var procResultParam = new System.Data.SqlClient.SqlParameter { ParameterName = \"@procResult\", SqlDbType = System.Data.SqlDbType.Int, Direction = System.Data.ParameterDirection.Output };");
        return sb.ToString();
    };

**Comment by arbh89** [comment]
Also i had to modify AddRelationship method to remove nameof function and it is working now.


```c#
    public static void AddRelationship(List<ForeignKey> fkList, Tables tablesAndViews, String relationshipName, String pkSchema, String pkTableName, String[] pkColumns, String fkSchema, String fkTableName, String[] fkColumns)
    {
        // Argument validation:
        if( fkList == null ) throw new ArgumentNullException("fkList");
        if( tablesAndViews == null ) throw new ArgumentNullException("tablesAndViews");
        if( String.IsNullOrEmpty(relationshipName) ) throw new ArgumentNullException("relationshipName");
        if( String.IsNullOrEmpty(pkSchema) ) throw new ArgumentNullException("pkSchema");
        if( String.IsNullOrEmpty(pkTableName) ) throw new ArgumentNullException("pkTableName");
        if( pkColumns == null ) throw new ArgumentNullException("pkColumns");
        if( pkColumns.Length == 0 || pkColumns.Any( s => String.IsNullOrEmpty(s) ) ) throw new ArgumentException("pkColumns");
        if( String.IsNullOrEmpty(fkSchema) ) throw new ArgumentNullException("fkSchema");
        if( String.IsNullOrEmpty(fkTableName) ) throw new ArgumentNullException("fkTableName");
        if( fkColumns == null ) throw new ArgumentNullException("fkColumns");
        if( fkColumns.Length != pkColumns.Length || fkColumns.Any( s => String.IsNullOrEmpty(s) ) ) throw new ArgumentException("fkColumns");

**Comment by sjh37** [comment]
This has now been released in v2.37.3
